# This worflow is scheduled for every hour, and also run after each commit (GitHub action excluded) on master/main branch

name: Metrics
on:
  schedule:
    - cron: "0 0-22/2 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics (additional)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: no
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: no
          plugin_languages: yes
          plugin_languages_ignored: Jupyter Notebook
          plugin_languages_skipped: lowlighter
          plugin_languages_details: bytes-size, percentage
          plugin_stargazers: no
          plugin_stars: yes
          plugin_stars_limit: 1
          config_timezone: America/New_York
          config_order: header, languages, pagespeed, habits, stars
          config_padding: 6%, 10%
